server:
  port: 6001

spring:
  application:
    name: productService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka
  instance:
      hostname: localhost
      instance-id: http://localhost:6001
