server:
  port: 4001

management:
  context-path: /admin

spring:
  application:
    name: cloud-config-server

  cloud:
    config:
      discovery:
        enabled: false
        service-id: configService
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          username: 123456
          password: 123456
          search-paths: config
  rabbitmq:
    username: 123456
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka








