server:
  port: 6004

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:bertondeng/Micro-Service-Architecture.git
          search-paths: config
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
    host: localhost
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka

  instance:
      hostname: localhost
      instance-id: localhost:6004








