server:
  port: 8088

spring:
  profiles:
    active: dev
  application:
    name: zuulService

zuul:
  routes:
    order:
      path: /orderService/**
      service-id: orderService
    product:
      path: /productService/**
      service-id: productService

