server:
  port: 8088

spring:
  application:
    name: zuulService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka

zuul:
  routes:
    order:
      path: /orderService/**
      service-id: orderService
    product:
      path: /productService/**
      service-id: productService

