server:
  port: 6002

spring:
  application:
    name: orderService

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka
  instance:
      hostname: localhost
      instance-id: http://localhost:6002